version: "3"

services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    admin:
        image: admin
        container_name: admin
        restart: always
        volumes:
            - ./data:/app/config
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ports:
            - "0.0.0.0:8080:8080"

    main:
        image: main
        container_name: main
        restart: always
        volumes:
            - ./data:/app/config
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ports:
            - "0.0.0.0:8081:8081"
